// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDka5myAYpWiP-hPR0MWE_s5_N1mPvhJ-E',
    appId: '1:222428272389:web:64219d831bd8ee4b6c096c',
    messagingSenderId: '222428272389',
    projectId: 'bullet-journal-8745',
    authDomain: 'bullet-journal-8745.firebaseapp.com',
    storageBucket: 'bullet-journal-8745.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONA0A6ogpo3m85eZYNVDZ4no7ZLAw3p4',
    appId: '1:222428272389:android:1d5b23f0031f851a6c096c',
    messagingSenderId: '222428272389',
    projectId: 'bullet-journal-8745',
    storageBucket: 'bullet-journal-8745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGD3FxAIf-EmjmWNBuKEZZEYG7SOuqgU',
    appId: '1:222428272389:ios:7c03bd81793d7a626c096c',
    messagingSenderId: '222428272389',
    projectId: 'bullet-journal-8745',
    storageBucket: 'bullet-journal-8745.appspot.com',
    iosClientId: '222428272389-lg6s6tt4ts8kj9mnid8ecgb6cr9e3du7.apps.googleusercontent.com',
    iosBundleId: 'com.patrycjakoscielniak.myBulletJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGD3FxAIf-EmjmWNBuKEZZEYG7SOuqgU',
    appId: '1:222428272389:ios:7c03bd81793d7a626c096c',
    messagingSenderId: '222428272389',
    projectId: 'bullet-journal-8745',
    storageBucket: 'bullet-journal-8745.appspot.com',
    iosClientId: '222428272389-lg6s6tt4ts8kj9mnid8ecgb6cr9e3du7.apps.googleusercontent.com',
    iosBundleId: 'com.patrycjakoscielniak.myBulletJournal',
  );
}
